CREATE TABLE FACULTIES
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE FACULTIES ADD CONSTRAINT FACULTIES_unique_ID UNIQUE (ID);
ALTER TABLE FACULTIES ADD CONSTRAINT FACULTIES_unique_NAME UNIQUE (NAME);