CREATE TABLE TESTS
(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    AUTHOR_ID INT NOT NULL,
    COMPLETED_SESSIONS_IDS INT NOT NULL,
    DISCIPLINE_ID INT NOT NULL,
    MINUTES_TO_PASS INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PUBLICATED BIT NOT NULL,
    QUESTIONS_IDS INT NOT NULL
);
ALTER TABLE TESTS ADD CONSTRAINT unique_ID UNIQUE (ID);