CREATE TABLE SESSIONS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TEST_ID BIGINT NOT NULL,
  STUDENT_ID BIGINT NOT NULL,
  START_DATE INT NOT NULL,
  COMPLETED_ID BIGINT NOT NULL,
  RESULT TINYINT NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE SESSIONS ADD CONSTRAINT unique_ID UNIQUE (ID);