CREATE TABLE USERS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  ROLE VARCHAR(256) NOT NULL,
  FIRST_NAME VARCHAR(256) NOT NULL,
  LAST_NAME VARCHAR(256) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL,
  PASSWORD_HASH VARCHAR(256) NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE USERS ADD CONSTRAINT unique_ID UNIQUE (ID);
ALTER TABLE USERS ADD CONSTRAINT unique_EMAIL UNIQUE (EMAIL);



CREATE TABLE DISCIPLINES
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TITLE VARCHAR(256) NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE DISCIPLINES ADD CONSTRAINT unique_ID UNIQUE (ID);
ALTER TABLE DISCIPLINES ADD CONSTRAINT unique_TITLE UNIQUE (TITLE);



CREATE TABLE TESTS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  AUTHOR_ID BIGINT NOT NULL,
  TITLE VARCHAR(256) NOT NULL,
  DISCIPLINE_ID BIGINT NOT NULL,
  MINUTES_TO_PASS TINYINT NOT NULL,
  PUBLICATED BOOLEAN NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE TESTS ADD CONSTRAINT unique_ID UNIQUE (ID);
ALTER TABLE DISCIPLINES ADD CONSTRAINT unique_TITLE UNIQUE (TITLE);



CREATE TABLE QUESTIONS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TEST_ID BIGINT NOT NULL,
  CONTENT VARCHAR(256) NOT NULL,
  TRUE_ID BIGINT NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE QUESTIONS ADD CONSTRAINT unique_ID UNIQUE (ID);



CREATE TABLE ANSWERS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  QUESTION_ID BIGINT NOT NULL,
  CONTENT VARCHAR(256) NOT NULL,
  CORRECT BOOLEAN NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE ANSWERS ADD CONSTRAINT unique_ID UNIQUE (ID);



CREATE TABLE SESSIONS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TEST_ID BIGINT NOT NULL,
  STUDENT_ID BIGINT NOT NULL,
  START_DATE INT NOT NULL,
  COMPLETED_ID BIGINT NOT NULL,
  RESULT TINYINT NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE SESSIONS ADD CONSTRAINT unique_ID UNIQUE (ID);
