CREATE TABLE TESTS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  AUTHOR_ID BIGINT NOT NULL,
  TITLE VARCHAR(256) NOT NULL,
  DISCIPLINE_ID BIGINT NOT NULL,
  MINUTES_TO_PASS TINYINT NOT NULL,
  PUBLICATED BOOLEAN NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE TESTS ADD CONSTRAINT unique_ID UNIQUE (ID);
ALTER TABLE DISCIPLINES ADD CONSTRAINT unique_TITLE UNIQUE (TITLE);