CREATE TABLE SESSION_ANSWERS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  SESSION_ID BIGINT NOT NULL,
  QUESTIONS_ID BIGINT NOT NULL,
  ANSWERS_ID BIGINT NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE SESSION_ANSWERS ADD CONSTRAINT SESSION_ANSWERS_unique_ID UNIQUE (ID);
ALTER TABLE SESSION_ANSWERS ADD CONSTRAINT SESSION_ANSWERS_unique_SESSION_ID UNIQUE (SESSION_ID);