CREATE TABLE TO_PASS_TESTS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  STUDENT_ID BIGINT NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE TO_PASS_TESTS ADD CONSTRAINT TO_PASS_TESTS_unique_ID UNIQUE (ID);