CREATE TABLE TYPES
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  NAME VARCHAR(256) NOT NULL
);
ALTER TABLE TYPES ADD CONSTRAINT unique_ID UNIQUE (ID);
ALTER TABLE TYPES ADD CONSTRAINT unique_NAME UNIQUE (NAME);