CREATE TABLE USERS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TYPE_ID BIGINT NOT NULL,
  FIRST_NAME VARCHAR(256) NOT NULL,
  FATHER_NAME VARCHAR(256) NOT NULL,
  LAST_NAME VARCHAR(256) NOT NULL,
  EMAIL VARCHAR(256) NOT NULL,
  PASSWORD_HASH VARCHAR(256) NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE USERS ADD CONSTRAINT USERS_unique_ID UNIQUE (ID);
ALTER TABLE USERS ADD CONSTRAINT USERS_unique_EMAIL UNIQUE (EMAIL);