CREATE TABLE ANSWERS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  QUESTION_ID BIGINT NOT NULL,
  CONTENT VARCHAR(256) NOT NULL,
  CORRECT BOOLEAN NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE ANSWERS ADD CONSTRAINT ANSWERS_unique_ID UNIQUE (ID);