CREATE TABLE CONFIGURATIONS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  TEST_ID BIGINT NOT NULL,
  MINUTES_TO_PASS TINYINT NOT NULL,
  QUESTION_COUNT_TO_VIEW TINYINT NOT NULL,
  SHUFFLE_QUESTION BOOLEAN NOT NULL,
  SHUFFLE_ANSWER BOOLEAN NOT NULL,
  SHOW_CORRECT BOOLEAN NOT NULL,
  TAKE_AGAIN BOOLEAN NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE CONFIGURATIONS ADD CONSTRAINT CONFIGURATIONS_unique_ID UNIQUE (ID);