CREATE TABLE TESTS
(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  AUTHOR_ID BIGINT NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  DISCIPLINE_ID BIGINT NOT NULL,
  CONFIGURATION_ID BIGINT NOT NULL,
  PUBLICATED BOOLEAN NOT NULL,
  DELETED BOOLEAN NOT NULL
);
ALTER TABLE TESTS ADD CONSTRAINT TESTS_unique_ID UNIQUE (ID);
ALTER TABLE TESTS ADD CONSTRAINT TESTS_unique_NAME UNIQUE (NAME);